Init Flask App
fablabjoinville/groselha pull request #1
Opened 2017-03-14 23:52 UTC by Dbastos1710

2017-03-14 23:53 UTC, alfakini requested changes

2017-03-14 23:53 UTC, alfakini commented on app.py
> +    return render_template('mac_addresses.html')
Esse aquivo não existe. Precisa adicionar ele ou então remover isso.

2017-03-14 23:56 UTC, alfakini approved these changes

2017-03-14 23:57 UTC, merged

2017-03-15 13:09 UTC, diogotrentini commented
👏 😄

2017-03-15 13:47 UTC, romuloab commented
> requirenments.txt

Não deveria ser `requirements.txt`?

2017-03-15 14:13 UTC, alfakini commented
Isso mesmo!

Alan Rafael Fachini
Magrathea Labs
www.magrathealabs.com
+55 47 99155-2269

On 15 Mar 2017 10:47 -0300, Romulo Amorim Bahiense <notifications@github.com>, wrote:
> > requirenments.txt
> Não deveria ser requirements.txt?
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-15 14:36 UTC, Dbastos1710 commented
Oops 😬
Arrumo depois......